test(Reducer): add reducer unit tests
brunakaufmann/Payflix pull request #12
Opened 2021-06-04 21:03 UTC by brunakaufmann

2021-06-04 21:05 UTC, brunobrt requested changes

2021-06-04 21:05 UTC, brunobrt commented on lib/models/tmdb_movies.dart
Pode remover o comentário por favor?

2021-06-04 21:07 UTC, brunobrt approved these changes

2021-06-07 20:46 UTC, AndreDrummer requested changes

2021-06-07 20:46 UTC, AndreDrummer commented on lib/redux/middleware.dart
> +        store.dispatch(IncrementPageAction(page));
Ué, toda vez que eu buscar filmes vou voltar pra página 1?

2021-06-09 12:55 UTC, AndreDrummer approved these changes

2021-06-09 14:24 UTC, HigorSegobia approved these changes

2021-06-09 14:25 UTC, merged